"""to_do_item table

Revision ID: 47465a88644d
Revises: 
Create Date: 2020-02-26 22:32:01.014783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47465a88644d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('to_do_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=150), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_to_do_item_completed'), 'to_do_item', ['completed'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_to_do_item_completed'), table_name='to_do_item')
    op.drop_table('to_do_item')
    # ### end Alembic commands ###
